# Generated by Django 4.2 on 2025-04-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Python', 'Python'), ('AWS', 'AWS'), ('Tally', 'Tally'), ('PowerBi', 'PowerBi')], default='Python', max_length=50, unique=True),
        ),
    ]
